### PR TITLE
creating new card in backlog

### PR DESCRIPTION
**Pull request by jeffkeelingbu**

### CODE REVIEW

**Comment by japarker02446** [comment]
Jeff, I saw the (last) message in Slack requesting the Card.id to be returned when a Card is created.  MongoDB does not return the ID when a new object is created (saved).  See https://docs.mongodb.com/manual/reference/method/db.collection.save/#writeresults-save

**Comment by DonCharest** [comment]
Hi Jeff, 
I had a similar issue, when creating a new project I wanted the list of projects to be updated without having to do a page refresh. For a work around,  I added this call to my onSubmit method to get all projects. 

`    setTimeout(() => {
      this.props.getProjects();
    }, 500);`

I added a timeout so that the update would happen before the refresh. Perhaps something like this would work for inserting a new card?

**Comment by japarker02446** [comment]
I've got an idea of how to  return the new card. At a birthday party with the little kid so can't implement.

I'm the card POST route, the aced object is created and saved. If you do a Card.find( ) on the parameters used to create it (description, user ID, etc) the find should return the newly created card object with all of its properties, including _id. 

If someone wants to implement this now it should work.  Just be sure to use 

await Card.find so the return waits for the data to come back. 

Jefferson

**Comment by japarker02446** [comment]
In the POST, doing a save( ) then a find( ) creates a nasty circular reference problem.  If you need to get the card ID first do the POST then do a GET with the same parameters and it should return the newly created card with the ID.  I have tested this locally with Postman.

**Pull request merged**
