### PR TITLE
Added auto short code from Project

### PR DESCRIPTION
**Pull request by japarker02446**
Added Card.title field
Removed default Card.stage.stageName = "BACKLOG", this is needed to allow creating Card from Sprint.
Pull Project.shortCode directly from Project.

### CODE REVIEW

**Comment by japarker02446** [comment]
Updated all returns to JSON objects containing:

**Comment by japarker02446** [comment]
I have tried many ways but it is not feasible to return a newly created card.  I tried to SAVE the card, then use the same parameters to find( ) the card and return it.  Doing this inside the same method call (POST or PUT) creates a circular reference error (https://makandracards.com/makandra/28847-dealing-with-typeerror-converting-circular-structure-to-json-on-javascript).

This does not resolve with any of the recommended methods.

HOWEVER, it is very easy to get the newly created object.  After you POST a NEW card, just GET the card using THE SAME PARAMETERS used in the POST (excluding stageName, or use stage.stageName as it is a sub-document).  Calling the POST then the GET does return the newly created card.

**Comment by japarker02446** [comment]
@jeffkeelingbu 
- Delete a card does work with the id in the request body.  I will work on updating the endpoint to DELETE api/cards/{id}.
- PUT the card does work.  You will have to refresh the card data to get it to show up (it only changes the database).
- See above for returning the new card (do a GET to get the _id).
- Setting the stage uses PUT api/cards/stagechange.  It's in the spreadsheet, maybe not payload doc.

**Comment by jeffkeelingbu** [comment]
@japarker02446 
- I'll appreciate when `DELETE api/cards/{id}` is added since our request library doesn't seem to support payloads in the request object on DELETE 
- I tested PUT `/api/cards` on both your branch and dev and and I'm sending an altered description field. And when i refresh the page, the field is still what it was before.
- Regarding saving the stage, I meant setting the state when creating a new card. Also, I would rather have setting the stage when editing a story be a part of  PUT `/api/cards` rather than be its own endpoint.

**Comment by japarker02446** [comment]
@jeffkeelingbu 

I tested PUT /api/cards on both your branch and dev and and I'm sending an altered description field. And when i refresh the page, the field is still what it was before.

- When you refresh the page are you pulling new data from the DB?  When I tested it locally the changes were saving to the DB.

Regarding saving the stage, I meant setting the stage when creating a new card. Also, I would rather have setting the stage when editing a story be a part of PUT /api/cards rather than be its own endpoint.

- Setting the stage on card creation is a thing now.
- Setting the stage as part of the PUT on api/cards is not advised as it has several moving parts (update the old stage, create the new stage, push the new stage to the stage array subdocument).

**Pull request merged**
