### PR TITLE
Add currentStage field to card, name of last stage

### PR DESCRIPTION
**Pull request by japarker02446**

### CODE REVIEW

**Comment by japarker02446** [comment]
@jeffkeelingbu 

I've added the card.currentStage field to indicate the stageName of the last entered stage.  When the stage is updated through PUT /api/cards/stagechange the card.currentStage field should also update.

I've edited the DELETE route to take the desired format '/api/cards/cardIdString' and tested this on local MongDB with Postman.

**Comment by japarker02446** [comment]
The UPDATE api/cards route has been fixed to allow MOST updates.  This route should return an error (500) and appropriate message if you try to use it to update: index, comment, related, stage or currentStage.  These have their own special routes because they are more involved (requires updating many cards, pushing to subdocument arrays or are inter-related).

**Comment by jeffkeelingbu** [comment]
@japarker02446 I restored my stage UI changes to this branch in order to test your changes.

- verified PUT and DELETE work now
- FYI, still encountered a card without currentStage being set. But the others were fine
- the `/stagechange` endpoint hangs and does not complete
- getting 500 on create new card. receiving this error
    `error: "Card save failed: Card validation failed: currentStage: Path `currentStage` is required., stage.0.stageName: Path `stageName` is required."`
Here's what im sending on that POST
Screen Shot 2019-07-16 at 6 46 21 PM

I'm good with merging this into `dev` if you want to address those changes on another branch

**Comment by japarker02446** [comment]
@jeffkeelingbu remove the stage.0.stageName and currentStage from input.  Just use 'stageName', that will populate both the stage array and the currentStage.

**Comment by jeffkeelingbu** [comment]
@japarker02446 still hanging passing in 
`{"id":"5d2bd447d9c72ae5fc019918","currentStage":"WORKINPROGRESS"}`

**Comment by japarker02446** [comment]
For api/changeStage the input should be a card Id and stageName.

**Comment by jeffkeelingbu** [comment]
Nevermind, im confusing myself. 

I will switch both PUT and POST to use stageName

**Comment by jeffkeelingbu** [comment]
@japarker02446 
PUT /stagechange `{"id":"5d2bd447d9c72ae5fc019918","stageName":"WORKINPROGRESS"}` is hanging

POST /cards  works

**Comment by japarker02446** [comment]
... is there a message returned or is it just failing?

**Comment by jeffkeelingbu** [comment]
@japarker02446 

So here's the deal. Sometimes it works. Might be related to switching to certain stages. You can see the ones hanging here
Screen Shot 2019-07-16 at 7 01 19 PM

**Comment by japarker02446** [comment]
oy, great ... intermittent bug ...
It's probably the end date of the prior stage.  If the original stage in the array has a partial success and sets and endDate then the search for the Card with stage.endDate == null will (... wait, is it ... '=' or '=='?) will fail.

**Comment by jeffkeelingbu** [comment]
should be `==` when doing a comparison

**Comment by japarker02446** [comment]
never mind, it's doing the json match

match the card with {
     "_id":req.body.id, 
     "stage.endDate":null
}

**Comment by japarker02446** [comment]
Yup, that card is dead for stageChange.  The end date has been set.

**Comment by japarker02446** [comment]
endDate != null, cannot find it to update it

image

**Comment by jeffkeelingbu** [comment]
@japarker02446 just made a new one. I think the end-date gets set to null after the first move?
Screen Shot 2019-07-16 at 7 39 27 PM

**Comment by japarker02446** [comment]
@jeffkeelingbu 
That is correct.  When you ADD a NEW stage, the prior stage gets endDate set to Date.now(), it just ended.  The NEW stage will have an endDate of null (it just started, hasn't ended).

**Comment by jeffkeelingbu** [comment]
@japarker02446 I'm not sure I understand. I thought you were saying the endDate being null was a problem. 

Is there anything I need to do on this?

**Comment by japarker02446** [comment]
Haha. No, the end Date being null on the current (last open) stage is a feature, not a bug.

When you go to update a stage it searches for the one that has an end date of null. This is the "current stage" before the stage change executes.

Step 1 is to give that stage an end date value. Step 2 is to create a NEW stage object (with end date null) and push this into the Card.stage array. 

If you begin a stage update with no stage having an empty end date it will fail.

**Pull request merged**
