### PR TITLE
Updates to Card and Sprint Routes

### PR DESCRIPTION
**Pull request by japarker02446**
Changed the GET Card route to take search parameters in a query string:
-- GET api/cards/?parameter=value

Changed the DELETE Card route to take the target Card ID as a query string:
- DELETE api/cards/?id=Card.id

Overhauled the Sprint route and model to be Sprint specific (no more cards from Sprint route)
- POST: Create a new Sprint requires start and end dates
- GET: Get a Sprint by Project._id, with project id in query string (api/sprint/?projectid=Project._id.  
-- The GET route will return the active Sprint where startDate >= Date.now() <= endDate.

### CODE REVIEW

**Comment by japarker02446** [comment]
These changes require changes to the UI:
- GET Cards for a project from the Card route by ProjectId (all cards for the Project)

**Comment by jeffkeelingbu** [comment]
@japarker02446 
I've pushed UI updates for the new route. On POST of a new card, I dont see it in the GET for cards. Once I can receive the cards, I will be able to test delete

**Comment by japarker02446** [comment]
@jeffkeelingbu Try something like GET on
http://localhost:3000/api/cards/?project=5d38ee7a2232fa42b007301a

The last bit is the project._id

**Comment by jeffkeelingbu** [comment]
@japarker02446 oh i needed to change the param from projectid to project. thanks

**Comment by japarker02446** [comment]
doh, yeah.  sorry, early unfortunate name choice

**Comment by japarker02446** [comment]
Updates to Card and Sprint functionality with appropriate front-end updates.

**Pull request merged**
